macro_rules! instantiators {
    ($name:ident: [$($parameter:ident),* $(,)?]) => {
        #[allow(non_snake_case)]
        pub mod $name {
            #[allow(unused)]
            pub const NAME: &'static str = stringify!($name);

            #[allow(unused)]
            pub const HASH: u32 = mm_hashing::hash_little32(NAME.as_bytes());

            #[allow(unused)]
            pub const PARAMETERS: &'static [Parameter] = &[
                $(Parameter::$parameter,)*
            ];

            #[allow(unused)]
            #[derive(Debug, Clone, Copy)]
            pub enum Parameter {
                $($parameter,)*
            }

            impl Into<usize> for Parameter {
                fn into(self) -> usize {
                    self as usize
                }
            }
        }
    };
    ($($name:ident: [$($parameter:ident),* $(,)?]),+ $(,)?) => {
        $(
            instantiators!($name: [$($parameter,)*]);
        )*
    };
}

instantiators!(
    CameraFacingBillboard: [
        LightInfluence,
        LightSaturation,
        LightTranslucency,
        FaceNormal,
        StartFadeOut,
        FadeOutInverse,
        StartFadeIn,
        FadeInInverse,
        CullHemisphere,
        CullHemisphereStart,
        CullHemisphereInverse,
        WidthScale,
        HeightScale,
        FrameRate,
        VelocityStretch,
        SizeMultiplierX,
        SizeMultiplierY,
        ParticleOffsetX,
        ParticleOffsetY,
        ParticleOffsetZ,
        Size,
        ErosionAgeRescale,
        MiddleVertexOffset,
        CameraVelocityWeight,
        FrameCount,
    ],
    CameraFacingBillboardBlend: [
        LightInfluence,
        LightSaturation,
        LightTranslucency,
        FaceNormal,
        StartFadeOut,
        FadeOutInverse,
        StartFadeIn,
        FadeInInverse,
        CullHemisphere,
        CullHemisphereStart,
        CullHemisphereInverse,
        WidthScale,
        HeightScale,
        FrameRate,
        VelocityStretch,
        SizeMultiplierX,
        SizeMultiplierY,
        ParticleOffsetX,
        ParticleOffsetY,
        ParticleOffsetZ,
        Size,
        ErosionAgeRescale,
        MiddleVertexOffset,
        CameraVelocityWeight,
        FrameCount,
    ],
    DecalEffect: [
        OffsetX,
        OffsetXSpread,
        OffsetY,
        OffsetYSpread,
        OffsetZ,
        OffsetZSpread,
        DiffuseWeight,
        NormalWeight,
        PropertiesWeight,
        SizeX,
        SizeXSpread,
        SizeY,
        SizeYSpread,
        Thickness,
        CollisionDistance,
        CollisionYaw,
        CollisionYawSpread,
        CollisionPitch,
        CollisionPitchSpread,
        CollisionRoll,
        CollisionRollSpread,
        CollisionOffset,
        TextureTileX,
        TextureTileY,
        TextureOffsetX,
        TextureOffsetY,
        ColorR,
        ColorG,
        ColorB,
        FadeOffset,
    ],
    EmbeddedEffect: [
        OffsetX,
        OffsetXSpread,
        OffsetY,
        OffsetYSpread,
        OffsetZ,
        OffsetZSpread,
        Bearing,
        BearingSpread,
        Height,
        HeightSpread,
    ],
    FullScreenEffect: [
        ColorCurveInfluence,
        ColorTintR,
        ColorTintG,
        ColorTintB,
        ColorTintHDR,
        ColorTintInfluence,
        Blur,
        BlurInfluence,
        BloomThreshold,
        BloomThresholdInfluence,
        BloomLighten,
        BloomLightenInfluence,
        BloomSecondaryLighten,
        BloomSecondaryLightenInfluence,
        BloomContract,
        BloomContractInfluence,
        RadialBlur,
        RadialBlurInfluence,
        RadialBlurOffset,
        RadialBlurOffsetInfluence,
        RadialBlurX,
        RadialBlurY,
        RadialBlurWorldX,
        RadialBlurWorldY,
        RadialBlurWorldZ,
        ViewAngle,
        ViewAngleCurve,
        ViewDistance,
        ViewDistanceCurve,
        LocalMin,
        LocalMax,
    ],
    LightEffect: [
        OffsetX,
        OffsetY,
        OffsetZ,
        Range,
        InnerRange,
        ColorR,
        ColorG,
        ColorB,
        ColorBrightness,
    ],
    ModelSpawn: [
        Lifetime,
        FadeDuration,
    ],
    ModelSpawnOnBirth: [
        Lifetime,
        FadeDuration,
    ],
    NormalMappedBillboard: [
        LightInfluence,
        LightSaturation,
        LightTranslucency,
        FaceNormal,
        StartFadeOut,
        FadeOutInverse,
        StartFadeIn,
        FadeInInverse,
        CullHemisphere,
        CullHemisphereStart,
        CullHemisphereInverse,
        WidthScale,
        HeightScale,
        FrameRate,
        VelocityStretch,
        SizeMultiplierX,
        SizeMultiplierY,
        ParticleOffsetX,
        ParticleOffsetY,
        ParticleOffsetZ,
        Size,
        ErosionAgeRescale,
        MiddleVertexOffset,
        CameraVelocityWeight,
        FrameCount,
    ],
    SimpleTrailInstantiator: [
        TextureRepeat,
        Duration,
        ColorR,
        ColorG,
        ColorB,
        ColorA,
        Width,
        Erosion,
        Framerate,
        LightSunMultiplier,
        LightEmissive,
        LightTranslucency,
    ],
    SoundEffect: [
        OffsetX,
        OffsetY,
        OffsetZ,
        InputValue0,
        InputValue1,
        InputValue2,
        InputValue3,
        InputValue4,
        InputValue5,
        InputValue6,
        InputValue7,
        TimeValue0,
        TimeValue1,
        TimeValue2,
        TimeValue3,
    ],
    SoundFocusEffect: [],
    SoundMixerEffect: [],
    TrailDespawn: [],
    TrailEffect: [
        Duration,
    ],
    VibrationEffect: [
        SmallValue,
        LargeValue,
        LeftTriggerValue,
        RightTriggerValue,
        ViewAngle,
        ViewAngleCurve,
        Distance,
        DistanceCurve,
        AmplitudeX,
        AmplitudeY,
        AmplitudeZ,
        AmplitudeMultiplier,
        Frequency,
        ViewAngleCamera,
        ViewAngleCameraCurve,
        DistanceCamera,
        DistanceCameraCurve,
    ],
    WorldFacingBillboard: [
        LightInfluence,
        LightSaturation,
        LightTranslucency,
        FaceNormal,
        StartFadeOut,
        FadeOutInverse,
        StartFadeIn,
        FadeInInverse,
        CullHemisphere,
        CullHemisphereStart,
        CullHemisphereInverse,
        WidthScale,
        HeightScale,
        FrameRate,
        VelocityStretch,
        SizeMultiplierX,
        SizeMultiplierY,
        ParticleOffsetX,
        ParticleOffsetY,
        ParticleOffsetZ,
        Size,
        ErosionAgeRescale,
        MiddleVertexOffset,
        CameraVelocityWeight,
        FrameCount,
    ],
    WorldFacingBillboardBlend: [
        LightInfluence,
        LightSaturation,
        LightTranslucency,
        FaceNormal,
        StartFadeOut,
        FadeOutInverse,
        StartFadeIn,
        FadeInInverse,
        CullHemisphere,
        CullHemisphereStart,
        CullHemisphereInverse,
        WidthScale,
        HeightScale,
        FrameRate,
        VelocityStretch,
        SizeMultiplierX,
        SizeMultiplierY,
        ParticleOffsetX,
        ParticleOffsetY,
        ParticleOffsetZ,
        Size,
        ErosionAgeRescale,
        MiddleVertexOffset,
        CameraVelocityWeight,
        FrameCount,
    ],
);
